import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactPlayer from 'react-player';
import { useState, useEffect } from 'react';

const Home: NextPage = () => {
  const [video, setVideo] = useState<any>(null);
  useEffect(() => {
    setVideo(listItems)}, [])

  const domain = "https://dbqzzcqmhmxm.cloudfront.net/";
  const ext = ".mp4";
  const videos = [
    // domain+"1"+ext,
    // domain+"2"+ext,
    // domain+"3"+ext,
    // domain+"4"+ext,
    // domain+"5"+ext,
    // domain+"6"+ext,
    domain+"7"+ext,
  ];


  const listItems = videos.map((v,index) =>
       <div key={index}>
        <div>
            Học tiếng anh qua phim hoạt hình
        </div>
        <ReactPlayer
         url={v}
         controls
         preload="none"
         width="700"
         height="480"
       >
        </ReactPlayer>
        </div>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.video}>
          {/* {listItems} */}
          {/* <div>{listItems}</div>; */}
          {/* <video src="https://dbqzzcqmhmxm.cloudfront.net/y2mate.com%20-%20AloKiddy%20T%E1%BB%AA%20V%E1%BB%B0NG%20TI%E1%BA%BENG%20ANH%20CH%E1%BB%A6%20%C4%90%E1%BB%80%20HOA%20QU%E1%BA%A2_1080p.mp4" controls></video> */}
          {video}
          {/* <ReactPlayer url="https://d3iqdl336k8b10.cloudfront.net/leetcode2022.mp4" controls={true} /> */}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
